# Generated by Django 4.1.5 on 2025-06-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_color_car_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
    ]
