# Generated by Django 5.2.2 on 2026-01-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
