# Generated by Django 5.2.2 on 2026-01-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_maintenance_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
